@startuml
!theme materia
actor User
actor Admin
database PostgresMovieData
database ElasticSearch
database Redis as redis_2
component AdminPanel
component Assistant_front
component Assistant_back
component LoadBalancer
component FastAPI
component ETL as etl_1

User -right-> Assistant_front: Запрос на просмотр контента
Assistant_front -right-> LoadBalancer
LoadBalancer -right-> Assistant_back
Assistant_back -right-> FastAPI: Запрос данных

FastAPI <--> ElasticSearch
FastAPI <--> redis_2: Cache

PostgresMovieData -up-> etl_1
etl_1 -down-> PostgresMovieData
etl_1 -up-> ElasticSearch
Admin -left-> AdminPanel: Редактирование данных
AdminPanel -left-> PostgresMovieData
@enduml