# Generated by Django 4.0.2 on 2022-08-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_created_genrefilmwork_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[
                ('actor', 'Actor'),
                ('director', 'Director'),
                ('writer', 'Writer')
            ], default='actor', max_length=12, verbose_name='role'),
        ),
    ]
