# Generated by Django 4.0.2 on 2022-08-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_genre_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(
                fields=['creation_date'],
                name='film_work_creation_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='genrefilmwork',
            index=models.Index(
                fields=['film_work', 'genre'],
                name='film_work_genre_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(
                fields=['film_work', 'person', 'role'],
                name='film_work_person_idx'
            ),
        ),
    ]
